store_server:
  build: .
  command: sh -c 'npm install; npm start'
  ports:
    - '3000:3000'
  volumes:
    - ./src:/srv/www/store_server
  links:
    - mongo
mongo:
  image: mongo
  ports:
  - '27017:27017'
