store_server:
  build: .
  command: sh -c 'npm install; npm start'
  environment:
    - PORT=$DOCKER_PORT
  ports:
    - '$DOCKER_PORT:$DOCKER_PORT'
  volumes:
    - ./src:/srv/www/store_server
  links:
    - mongo
mongo:
  image: mongo
  ports:
  - '27017:27017'
